### ISSUE TITLE
Acces Blocked

### ISSUE THREAD

**Issue by mxmlnlrcn** [pxtrez/kaheet#1]
Hi, 

Thanks for this code but, when I try to run it , I get this error

`Access to fetch at 'https://kaheet.herokuapp.com/v1/api/version/2.0.0' from origin 'https://kahoot.it' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

What it means? Thanks

**Comment by pxtrez** [comment]
Hello, thanks for creating the issue.
I fixed the api script, so now it should work fine.
Btw, I made a big update for kaheet.
Before use, be sure to read the [instructions](https://github.com/pxtrez/README.md)
I hope you like it!

**Comment by pxtrez** [comment]
> Hi,
> 
> Thanks for this code but, when I try to run it , I get this error
> 
> `Access to fetch at 'https://kaheet.herokuapp.com/v1/api/version/2.0.0' from origin 'https://kahoot.it' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
> 
> What it means? Thanks

works?

**Comment by mandy3110** [comment]
Hi, 
Thanks for the code, I tried testing it out and it worked great.
But, this works only on the public quizzes on Kahoot. What if i know the uuid/quizid of a private Quiz, it is not working for it currently.
The host usually keeps the quiz private. :(
