### ISSUE TITLE
can i get the name before the game start?

### ISSUE THREAD

**Issue by wadawaka** [pxtrez/kaheet#4]
Hi,
Thanks for the code, I tried testing it out and it worked great.
But, if i cant see the quizid?, you put other code to get that with que name, but, can i find the name of the quizz before the game start? because im triying to win a prize with some quiz on kahoot, but if im need to be fast to answer

**Comment by pxtrez** [comment]
Hi,
First, let me tell you that cheat doesn't work with private quizzes.

Okay, when you join a game, in Dev Tools under the Network tab you should see a websocket connection. You can find it by pressing ctrl + f and typing ws or websocket. Then click on it and go to the Messages tab. There you will find the name of the quiz.

This method should work. I'm not at home and I don't have a computer with me, so I have no way to verify that what I wrote works well.

**Comment by pxtrez** [comment]
maybe i will try to make another script for it

**Comment by pxtrez** [comment]
ok, i just checked and what i wrote doesn't make sense, it doesn't work anymore. I have no clue how to get it

**Comment by pxtrez** [comment]
I do not see any way, I close the issue
